<a href="https://colab.research.google.com/github/DgBack/Deep-learning-Tutorial-with-Python-Basic/blob/main/1_Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Gọi thư viện Numpy 

In [1]:
import numpy as np 

Gọi mảng hai chiều và mảng một chiều 

In [2]:
# Mảng một chiều 
one_np = np.array([10, 20, 30, 40])
print(one_np)

[10 20 30 40]


In [4]:
# Mảng hai chiều 
two_np = np.array([[10, 20 , 30],
                  [40, 50, 60]])
print(two_np)

[[10 20 30]
 [40 50 60]]


In [5]:
# In ra type của hai ma trận 
print(type(one_np))

print(type(two_np))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Khởi tạo các ma trận với các cú pháp đặc biệt 


In [6]:
# Trước hết chúng ta tạo mảng với khai báo điểm đầu và điểm kết thúc 

arr_np = np.arange(10, 20 )
print(arr_np)

[10 11 12 13 14 15 16 17 18 19]


In [7]:
# Ngoài ra ta cũng có thể tạo mảng kiểu trên kết hợp với bước nhảy

arr_step_np = np.arange(10, 30, 5)
print(arr_step_np)

[10 15 20 25]


In [8]:
# Xây dựng mảng với các số ngẫu nhiên 
random_arr = np.random.randint(1, 200, 5)
print(random_arr)

[ 38  99  70  19 166]


In [9]:
# Xây dựng mảng với hàm np.full((chiều dọc, chiều ngang), giá trị một đơn vị)
full_np = np.full((4, 8), 5)
print(full_np)

[[5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]]


Kiểm gia số lượng dạng của ma trận 


In [10]:
# Để kiểm tra dạng của ma trận ta có thể sử dụng hàm shape để hiện lên số hàng và số cột 
# Ta thử nghiệm với các ma trận mà ta đã gọi ở bên trên 

two_np.shape

(2, 3)

Ngoài ra thì ta có một số hàm đặc biệt khá nữa đó là vstack(), hstack() và column_stack() 



In [11]:
# Trước hết là với hàm vstack(), nó sẽ nối hai hàm lại với nhau nhưng kiểu chập lịa thành mảng nhiều hai chiều á
n1 = np.array([10, 20, 30])
n2 = np.array([40, 50, 60])

np.vstack((n1, n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [12]:
# Đến với hstack(), đây sẽ kiểu là nối các ma trận lại với nhau ngược lại so với vstack()
np.hstack((n1, n2))

array([10, 20, 30, 40, 50, 60])

In [13]:
# Đến với hàm column_stack(), đi ngược lại hướng của vstack()
np.column_stack((n1, n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [14]:
# Ta xét đến hàm intersectid, hàm này lấy những phần tử chung của hai ma trận 
n1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
n2 = np.array([7, 8, 9, 10, 11, 12])

np.intersect1d(n1, n2)

array([7, 8, 9])

In [15]:
# Tính tổng 
n1 = np.array([10, 20])
n2 = np.array([30, 40])

np.sum([n1, n2])

np.sum([n1, n2], axis = 0)
np.sum([n1, n2], axis = 1)

array([30, 70])